version: 2.1

anchors:
  docker:
    dotnet_docker: &dotnet_docker
      docker:
        - image: mcr.microsoft.com/dotnet/core/sdk:3.1

jobs:
  build:
    <<: *dotnet_docker
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: dotnet build

workflows:
  version: 2
  build:
    jobs:
      - build
