name: Build and publish docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA:0:9})

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/GiganticMinecraft/inventory-search
          username: GiganticMinecraft
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
