name: Build and publish docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build docker image
        run: docker build -t docker.pkg.github.com/GiganticMinecraft/InventorySearch/inventory-search:${{ GITHUB_SHA }} .

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/GiganticMinecraft/InventorySearch/inventory-search:${{ GITHUB_SHA }}
          username: GiganticMinecraft
          password: ${{ secrets.GITHUB_TOKEN }}
